# Generated by Django 3.2.5 on 2021-07-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
