# Generated by Django 3.2.5 on 2021-07-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_login_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
